// Auto-generated by MakeAFont. Builds a Unity Font asset from an AngelCode
// .fnt descriptor plus its atlas page, preserving per-glyph size, offsets and advance.
#if UNITY_EDITOR
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class BitmapFontImporter
{
    [MenuItem("Tools/MakeAFont/Build Font From .fnt")]
    public static void BuildFont()
    {
        string fntPath = EditorUtility.OpenFilePanel("Pick font.fnt", Application.dataPath, "fnt");
        if (string.IsNullOrEmpty(fntPath)) return;
        if (!fntPath.StartsWith(Application.dataPath))
        {
            EditorUtility.DisplayDialog("MakeAFont", "Pick a .fnt inside this project's Assets folder.", "OK");
            return;
        }

        string assetDir = "Assets" + Path.GetDirectoryName(fntPath).Substring(Application.dataPath.Length).Replace('\\', '/');
        var lines = File.ReadAllLines(fntPath);

        string page = "atlas.png";
        int lineHeight = 0, baseLine = 0, scaleW = 0, scaleH = 0;
        var glyphs = new List<CharacterInfo>();

        foreach (var raw in lines)
        {
            var line = raw.Trim();
            if (line.StartsWith("common "))
            {
                lineHeight = Field(line, "lineHeight");
                baseLine = Field(line, "base");
                scaleW = Field(line, "scaleW");
                scaleH = Field(line, "scaleH");
            }
            else if (line.StartsWith("page "))
            {
                int q = line.IndexOf("file=\"");
                if (q >= 0)
                {
                    int end = line.IndexOf('"', q + 6);
                    if (end > q) page = line.Substring(q + 6, end - q - 6);
                }
            }
            else if (line.StartsWith("char id="))
            {
                int id = Field(line, "id");
                int x = Field(line, "x"), y = Field(line, "y");
                int w = Field(line, "width"), h = Field(line, "height");
                int xo = Field(line, "xoffset"), yo = Field(line, "yoffset");
                int adv = Field(line, "xadvance");
                if (w <= 0 || h <= 0)
                {
                    // Advance-only glyph (space): no art, but it still moves the pen.
                    glyphs.Add(new CharacterInfo { index = id, advance = adv });
                    continue;
                }
                var info = new CharacterInfo { index = id, advance = adv };
                // Unity's UV rect is normalised with the origin at the BOTTOM-left.
                info.uvBottomLeft = new Vector2(x / (float)scaleW, 1f - (y + h) / (float)scaleH);
                info.uvBottomRight = new Vector2((x + w) / (float)scaleW, 1f - (y + h) / (float)scaleH);
                info.uvTopLeft = new Vector2(x / (float)scaleW, 1f - y / (float)scaleH);
                info.uvTopRight = new Vector2((x + w) / (float)scaleW, 1f - y / (float)scaleH);
                // Vertical offsets run UP from the baseline in Unity, DOWN from the
                // line top in a .fnt, so the sign flips here.
                info.minX = xo;
                info.maxX = xo + w;
                info.maxY = baseLine - yo;
                info.minY = baseLine - yo - h;
                glyphs.Add(info);
            }
        }

        string texPath = assetDir + "/" + page;
        var tex = AssetDatabase.LoadAssetAtPath<Texture2D>(texPath);
        if (tex == null)
        {
            EditorUtility.DisplayDialog("MakeAFont", "Could not find " + texPath, "OK");
            return;
        }
        var ti = (TextureImporter)AssetImporter.GetAtPath(texPath);
        if (ti != null)
        {
            ti.filterMode = FilterMode.Point;
            ti.textureCompression = TextureImporterCompression.Uncompressed;
            ti.alphaIsTransparency = true;
            ti.SaveAndReimport();
        }

        var mat = new Material(Shader.Find("GUI/Text Shader")) { mainTexture = tex };
        string matPath = assetDir + "/font.mat";
        AssetDatabase.CreateAsset(mat, matPath);

        var font = new Font(Path.GetFileNameWithoutExtension(fntPath));
        font.material = mat;
        font.characterInfo = glyphs.ToArray();
        string fontPath = assetDir + "/font.asset";
        AssetDatabase.CreateAsset(font, fontPath);

        var so = new SerializedObject(font);
        var lh = so.FindProperty("m_LineSpacing");
        if (lh != null) { lh.floatValue = lineHeight; so.ApplyModifiedProperties(); }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();
        Debug.Log("MakeAFont: built " + fontPath + " with " + glyphs.Count + " glyphs.");
    }

    static int Field(string line, string key)
    {
        foreach (var tok in line.Split(' '))
        {
            if (!tok.StartsWith(key + "=")) continue;
            var v = tok.Substring(key.Length + 1).Trim('"');
            if (int.TryParse(v, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n)) return n;
        }
        return 0;
    }
}
#endif